name: Test Flask with Secret
on: [push]
jobs:
  Test-Flask-With-Secret:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          cd Google_API_1  
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Flask with Secret
        shell: bash
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          FLASK_APP: main
        run: |
          cd Google_API_1
          gunicorn -b 127.0.0.1:5000 --daemon main:app
          curl http://127.0.0.1:5000/api/routing?originLat=1.31&originLong=103.75&destinLat=1.32&destinLong=103.76
      - run: echo "ğŸ This job's status is ${{ job.status }}."
